_name_: gene_identification
bed_file: /scratch/kyle/hyena-dna/data/hg38/equences.bed
fasta_file: /scratch/kyle/hyena-dna/data/hg38/hg38.ml.fa
ref_labels_file: /scratch/kyle/hyena-dna/data/hg38/hg38.refGene.gtf
max_length: 1000000
batch_size: 1
shuffle: True
__train_len: 38171  
__l_max: ${eval:${.max_length}}

