model_checkpoint:
  save_top_k: -1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  dirpath: "/scratch/kyle/hyena-dna/checkpoints/"
  save_weights_only: True  # Only save model weights
  every_n_epochs: 1  # Save checkpoint after every epoch
  verbose: True
  filename: model-{epoch:02d}